name: polyzymd-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - openeye
dependencies:
  - python=3.11

  # CUDA-enabled PyTorch
  #- pytorch
  #- pytorch-cuda=12.1    # match your driver and DGL CUDA builds

  # Core scientific stack
  - numpy
  - pandas
  - matplotlib
  - pillow
  - jupyterlab
  - ipywidgets=8.0.4
  - rdkit
  - openmm
  - mdtraj
  - mbuild
  - openbabel
  - packmol<=20.15.1
  - openeye-toolkits
  - pint

  # DGL CUDA build
  - dgl=2.1.0  # auto-selects cu121 since pytorch-cuda=12.1 is installed

  # OpenFF stack (conda only)
  - openff-toolkit>=0.16
  - openff-interchange>=0.4
  - openff-nagl>=0.5
  - openff-nagl-models>=0.3
  - espaloma_charge>=0.0.8

  # Useful utils
  - pdbfixer

  # Python libs
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pytest-cov
  - codecov
  - py3Dmol
  - nglview=3.0.6
  - cirpy
  - pubchempy
  - torchdata<=0.10.0
  - pip
  - pip:
      - polymerist
